// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AwardsMarquee: typeof import('./components/awardsMarquee/index.vue')['default']
    CustomDialog: typeof import('./components/CustomDialog/index.vue')['default']
    Dialog: typeof import('./components/Dialog/index.vue')['default']
    DialogCustom: typeof import('./components/DialogCustom/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
